still broken amr version, de/allocateBflux
Running into this error, which is primarily related to openacc not being
able to destroy and/or allocate deallocate the fluxalloc structure
correctly ...

allocated block device:0x15256bfffe00 size:512 thread:1
deleted block   device:0x152370f0f800 size:7680 threadid=1
deleted block   device:0x15236120f200 size:13824 threadid=1
deleted block   device:0x152370e57e00 size:207360 threadid=1
deleted block   device:0x152364000000 size:18432000 threadid=1
deleted block   device:0x152360000000 size:18432000 threadid=1
deleted block   device:0x152362000000 size:18432000 threadid=1
deleted block   device:0x152366000000 size:159252480 threadid=1

Present table errors:
array(:) lives at 0x39f8fbb0 size 24 partially present in
host:0x39f8f940 device:0x152370d5e000 size:640 presentcount:0+1 line:848 name:pflux%flux(:,:,:,:) file:/home/jvos1/v1_AGILE/AGILE-experimental/src/mod_fix_conserve.fpp
FATAL ERROR: variable in data clause is partially present on the device: name=array(:)
 file:/home/jvos1/v1_AGILE/AGILE-experimental/src/mod_acc_utils.fpp copy_or_update_logical_pointer_r1 line:172